/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalaryCompFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MainFrame.MAXIMIZED_BOTH);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnllSideBar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PayrollTab = new javax.swing.JButton();
        pnlEmployeeSubmenu = new javax.swing.JPanel();
        btnAddEmployee = new javax.swing.JButton();
        btnDelEmployee = new javax.swing.JButton();
        btnViewEmployee = new javax.swing.JButton();
        btnEmployeeManagement1 = new javax.swing.JButton();
        SalaryCompTab1 = new javax.swing.JButton();
        PayslipTab = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(209, 209, 209));
        setForeground(new java.awt.Color(209, 209, 209));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1440, 1024));

        pnlHeader.setBackground(new java.awt.Color(255, 251, 251));
        pnlHeader.setForeground(new java.awt.Color(255, 251, 251));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1200, 110));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1440, 153));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_system/554311662_1317130376082826_1071741920614451639_n 1.png"))); // NOI18N
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BARANGAY SAN ROQUE, CAINTA, RIZAL");
        pnlHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 890, 150));

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnllSideBar.setBackground(new java.awt.Color(11, 11, 69));
        pnllSideBar.setPreferredSize(new java.awt.Dimension(290, 871));
        pnllSideBar.setVerifyInputWhenFocusTarget(false);
        pnllSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("System");
        pnllSideBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 40));

        PayrollTab.setBackground(new java.awt.Color(11, 11, 69));
        PayrollTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PayrollTab.setText("Payroll");
        PayrollTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(PayrollTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        pnlEmployeeSubmenu.setBackground(new java.awt.Color(14, 14, 86));
        pnlEmployeeSubmenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 14, 86), 1, true));
        pnlEmployeeSubmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnAddEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        btnDelEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnDelEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDelEmployee.setText("Delete Employee");
        pnlEmployeeSubmenu.add(btnDelEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 30));

        btnViewEmployee.setBackground(new java.awt.Color(14, 14, 86));
        btnViewEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmployee.setText("View Employee");
        btnViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeSubmenu.add(btnViewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 30));

        pnllSideBar.add(pnlEmployeeSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        btnEmployeeManagement1.setBackground(new java.awt.Color(11, 11, 69));
        btnEmployeeManagement1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmployeeManagement1.setText("Employee Management     ▼");
        btnEmployeeManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManagement1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(btnEmployeeManagement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        SalaryCompTab1.setBackground(new java.awt.Color(11, 11, 69));
        SalaryCompTab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SalaryCompTab1.setText("Salary Computation");
        SalaryCompTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryCompTab1ActionPerformed(evt);
            }
        });
        pnllSideBar.add(SalaryCompTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, -1));

        PayslipTab.setBackground(new java.awt.Color(11, 11, 69));
        PayslipTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PayslipTab.setText("Payslip");
        PayslipTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayslipTabActionPerformed(evt);
            }
        });
        pnllSideBar.add(PayslipTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setText("Payroll");
        pnllSideBar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("Management");
        pnllSideBar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 40));

        getContentPane().add(pnllSideBar, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1038, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PayrollTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayrollTabActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnEmployeeManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManagement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeManagement1ActionPerformed

    private void SalaryCompTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryCompTab1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryCompTab1ActionPerformed

    private void PayslipTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayslipTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayslipTabActionPerformed

    private void btnViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PayrollTab;
    private javax.swing.JButton PayslipTab;
    private javax.swing.JButton SalaryCompTab1;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDelEmployee;
    private javax.swing.JButton btnEmployeeManagement1;
    private javax.swing.JButton btnViewEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlEmployeeSubmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnllSideBar;
    // End of variables declaration//GEN-END:variables
}
